config/routes.rb
Alexandria::Application.routes.draw do
  resources :documents, :only => [:show, :index]

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  
  attr_accessible :name
end

app/models/document.rb
class Document < ActiveRecord::Base
  acts_as_taggable

  validates :filename, :checksum, :timestamp, :presence => true
  validates :checksum, :uniqueness => true
  
  attr_accessible :filename, :thumbnail, :checksum, :name, :description, :timestamp, :imported_at, :archived_at, :archive_id
  
  def self.available_years
    self.select("distinct year(timestamp) as year_timestamp").collect {|d| d.year_timestamp }
  end

  def self.available_months(year)
    self.where(["year(timestamp) = ?", year]).select("distinct month(timestamp) as month_timestamp").collect {|d| d.month_timestamp }
  end

  def self.type_for(path)
    extension = File.extname(path).downcase
    {".jpg" => Photo,
      ".jpeg" => Photo}[extension] || Document
  end

  def self.timestamp_for(path)
    timestamp = File.mtime(path)
  end
  
  def self.import!(path, tags, options)
    result = options[:result]

    # first, we get the checksum and skip if its a dup.
    sha256sum = Digest::SHA256.new
    file = File.open(path, 'rb')
    sha256sum << file.read()
    file.close
    
    checksum = sha256sum.to_s
    if (document = Document.find_by_checksum(checksum))
      tag_list = (document.tag_list + tags).uniq
      result[:skipped] += 1
      document.tag_list = tag_list
      document.save!
      Rails.logger.info("#{path} skipped, file already exists: #{document.library_filename}")
      return
    end
    
    # Not a dup. Create the document object
    type = self.type_for(path)
    timestamp = type.timestamp_for(path)
    ext = File.extname(path)
    name = File.basename(path, ext)
    timestamp_path = timestamp.strftime("%Y/%m")
    destination_filename = File.join(timestamp_path, "#{checksum}#{ext.downcase}")
    
    document = type.new(:filename => destination_filename, :checksum => checksum, :name => name, :timestamp => timestamp)
    document.tag_list += tags
    
    if document.valid?
      file_base_path = File.join(BASE_PATH, timestamp_path)
      FileUtils.mkdir_p(file_base_path)
      FileUtils.cp(path, File.join(BASE_PATH, destination_filename))
      document.save!
    else
      Rails.logger.error("imported document invalid for path: #{path}")
      result[:errors] += 1
    end
  end

  def self.import_file(path, tags, options={})
    result = {:errors => 0, :total => 0, :skipped => 0}

    if File.file?(path)
      result[:total] += 1
      self.import!(path, tags, options.merge(:result => result))
    elsif File.directory?(path)
      Dir.glob(File.join(path, "**", "*")).each do |name|
        next unless File.file?(name)
        relative_path = File.dirname(name)[path.length..-1] || ""
        path_tags = relative_path.split("/").select {|n| !n.blank? }
        image_tags = (tags + path_tags).collect {|t| t.downcase }.uniq
        
        result[:total] += 1
        self.import!(name, image_tags, options.merge(:result => result))
      end
      Rails.logger.info "import in progress: #{result.inspect}" if result[:total]%100==0
    end
    Rails.logger.info "import done: #{result.inspect}"
    result
  end

  def library_filename
    File.join(BASE_PATH, filename)
  end
end

app/models/exif_data.rb
class ExifData < ActiveRecord::Base
  belongs_to :photo
  serialize :exif_data

  attr_accessible :exif_data

end

app/models/photo.rb
class Photo < Document
  has_one :photo_information, :dependent => :destroy
  
  after_create :create_photo_information

  belongs_to :album

  def self.timestamp_for(path)
    timestamp = nil
    begin
      exif_data = EXIFR::JPEG.new(path)
      if exif_data.exif?
        exif_data = exif_data.to_hash
        timestamp = exif_data[:date_time] || exif_data[:date_time_original] || exif_data[:date_time_digitized]
      end
    rescue Exception => e
      Rails.logger.error "could not read exif data from: #{path}"
      timestamp = nil
    end
    timestamp = File.mtime(path) if timestamp.blank?
    timestamp
  end

  private

  def create_photo_information
    self.build_photo_information.save!
  end
  
end

app/models/photo_information.rb
class PhotoInformation < ActiveRecord::Base
  belongs_to :photo
  belongs_to :roll

  before_create :extract_exif_info

  before_save :assign_roll

  after_save :modify_roll_timestamps
  
  serialize :exif_data, Hash
  
  private
  def extract_exif_info
    self.exif_data = {}
    begin
      data = EXIFR::JPEG.new(self.photo.library_filename)
    
      if data.exif?
        self.exif_data = data.to_hash
      end
    rescue Exception => e
      Rails.logger.error "could not read exif data from: #{self.photo.library_filename}"
    end
  end
  
  def assign_roll
    self.roll = Roll.find_or_create_roll_for(self.photo.timestamp)
  end

  def modify_roll_timestamps
    if self.photo.timestamp < self.roll.started_at
      self.roll.update_attributes!(:started_at => self.photo.timestamp)
    elsif self.photo.timestamp > self.roll.finished_at
      self.roll.update_attributes!(:finished_at => self.photo.timestamp)
    end    
  end

end

app/models/roll.rb
class Roll < ActiveRecord::Base
  attr_accessible :started_at, :finished_at, :name
  
  validates :started_at, :finished_at, :presence => true
  validates :name, :uniqueness => true
  
  validate :validate_roll_timestamps
  
  has_many :photo_informations

  def self.find_or_create_roll_for(timestamp)
    max_roll = Roll.last
    max_roll_id = max_roll ? max_roll.id : 0
    rolls = self.roll_for_timestamp(timestamp).all
    if rolls.length > 1
      roll = self.merge_rolls!(rolls)
    elsif rolls.length == 1
      roll = rolls.first
    else
      roll = Roll.create!(:started_at => timestamp, :finished_at => timestamp, :name => "Roll #{max_roll_id + 1}")
    end
    roll
  end

  private
  def self.roll_for_timestamp(timestamp)
    self.where("? between date_sub(started_at, interval 1 day) and date_add(finished_at, interval 1 day)", timestamp)
  end

  def self.merge_rolls!(rolls)
    destination_roll = rolls.first

    rolls[1..-1].each do |roll|
      roll.photo_informations.each do |photo_information|
        photo = photo_information.photo
        if photo.timestamp < destination_roll.started_at
          destination_roll.started_at = photo.timestamp
        elsif photo.timestamp > destination_roll.finished_at
          destination_roll.finished_at = photo.timestamp
        end
      end
      PhotoInformation.where(:roll_id => roll.id).update_all(:roll_id => destination_roll.id)
      roll.destroy
    end
    
    destination_roll.save!
    destination_roll
  end
  
  def validate_roll_timestamps
    return unless self.started_at && self.finished_at

    if self.started_at > self.finished_at
      errors.add(:started_at, "cannot be greater than finished_at")
    end
    id_condition = self.new_record? ? "" : "id <> #{self.id}"
    if Roll.roll_for_timestamp(self.started_at).where(id_condition).count > 0
      errors.add(:started_at, "cannot overlap with other roll's timerange")
    end
    
    if Roll.roll_for_timestamp(self.finished_at).where(id_condition).count > 0
      errors.add(:finished_at, "cannot overlap with other roll's timerange")
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @available_years = Document.available_years
    @year = params[:year].to_i if params[:year] && @available_years.include?(params[:year].to_i)
    if @year
      @available_months = Document.available_months(@year)
    end
    @month = params[:month].to_i if params[:month] && @available_months.include?(params[:month].to_i)
    
    @documents = Document.order(:timestamp)
    @documents = @documents.where(["year(timestamp) = ?", @year]) if @year
    @documents = @documents.where(["month(timestamp) = ?", @month]) if @month
    @documents = @documents.paginate(:page => params[:page])
  end

  def show
    @document = Document.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_document_preview.html.erb
<div class='document_preview'>
    <div class='attr name'><%=link_to(document_preview.name, document_path(document_preview))%></div>
    <div class='attr type'>(<%=document_preview.type%>)</div>
    <div class='attr timestamp'><%=document_preview.timestamp.to_s(:db)%></div>
    <div class='attr tags'><%=document_preview.tag_list.join(",") %></div>
    <div style='clear:both;'></div>
</div>

app/views/documents/_left_meta.html.erb
<div class = 'left_meta page_left'>
    <div class='name'><%=document.name%></div>
    <div class='timestamp'><%=document.timestamp%></div>
    <div class='tags'><%=document.tag_list%></div>
    
    <% if document.is_a?(Photo) %>
        <%= render :partial => 'photo_information', :locals => {:photo => document} %>
    <% end %>
</div>

app/views/documents/_left_nav.html.erb
<div class='left_nav page_left'>
    <% @available_years.each do |year| %>
        <% if @year && @year == year %>
            <div class='selected year'>
                <%= year %>
                <% @available_months.each do |month| %>
                    <% if @month && @month == month %>
                        <div class='selected month'><%= month %></div>
                    <% else %>
                        <div class='month'><%= link_to(month, documents_path(:year => year, :month => month)) %></div>
                    <% end %>
                <% end %>
            </div>
        <% else %>
            <div class='year'>
                <%= link_to(year, documents_path(:year => year)) %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/documents/_photo_information.html.erb
<% if !photo.photo_information.exif_data.blank? %>
    <div class='photo_information'>

        <% photo.photo_information.exif_data.each do |key,value| %>
            <% value = value.to_i if key==:orientation %>
            <div class='exif_attr'>
                <span class='label'><%=key%>: </span><span class='value'><%=value.to_s%></span>
            </div>
        <% end %>
    </div>
<% end %>

app/views/documents/index.html.erb
<div id='doc_idx'>
    
    <%= render :partial => 'left_nav' %>
    
    <div id='doc_list' class='list_view page_middle'>
        <div class='labels'>
            <div class='label name'>Name</div>
            <div class='label type'>Type</div>
            <div class='label timestamp'>Timestamp</div>
            <div class='label tags'>Tags</div>
            <div style='clear:both;'></div>
        </div>
        
        <%= render :partial => 'document_preview', :collection => @documents %>
        
        <%= will_paginate @documents %>
    </div>
</div>

app/views/documents/show.html.erb
<div id='doc_show'>
    <%= render :partial => 'left_meta', :locals => {:document => @document} %>
    
    <div class='document' class='page_middle'>
        <% if @document.is_a?(Photo) %>
        <%= image_tag("/library/#{@document.filename}", :width => "700px", :alt => @document.name) %>
        <% else %>
            Document view for type <%= @document.class.name %> not yet available.
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>The Alexandria Project</title>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class='head'>
            The Alexandria Project
        </div>
        
        <div class='universe'>
            
            <%= yield %>
            
            <div style='clear:both'></div>
        </div>
        
    </body>
    
</html>